# This file was generated by GoReleaser. DO NOT EDIT.
cask "relay" do
  version "0.3.0"

  on_macos do
    on_arm do
      sha256 "9d8833b54f5ac883b69e16e047f86100f1060435ad4e9dae183737d8dfe4cf88"
      url "https://github.com/relay-sh/homebrew-tap/releases/download/v#{version}/relay_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "72685d8cfdfe357b6e3210d77323c6f0ecf788c368474ef968812299baf4e00e"
      url "https://github.com/relay-sh/homebrew-tap/releases/download/v#{version}/relay_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "4687410e4fe1742f579bc7369b21ac8463a1e2cec70a0b0acca7c79dec81c872"
      url "https://github.com/relay-sh/homebrew-tap/releases/download/v#{version}/relay_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "2f298f516cca495f6f5a1a8c414d671d89989b602108d73ba72d0029d28e9e4a"
      url "https://github.com/relay-sh/homebrew-tap/releases/download/v#{version}/relay_#{version}_linux_amd64.tar.gz"
    end
  end

  name "relay"
  desc "Relay CLI — connect to databases through Relay agents with data masking"
  homepage "https://userelay.sh"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "relay"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/relay"]
    end
  end

  # No zap stanza required
end
