# This file was generated by GoReleaser. DO NOT EDIT.
cask "relay" do
  version "0.2.0"

  on_macos do
    on_arm do
      sha256 "326f0c35bff78a0ab78a56ca400bc474edd486e6f6f2872db6734fc70fc33cc2"
      url "https://github.com/relay-sh/homebrew-tap/releases/download/v#{version}/relay_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "1a311a3eae08da77975528aa9fee54ee3ae1888a817bbcc8e7a3a3c0508060b9"
      url "https://github.com/relay-sh/homebrew-tap/releases/download/v#{version}/relay_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_intel do
      sha256 "525d17fa094b9e90e87fc7e55cecdbc373dbf5dd35287b4aef4319cd0e8afe93"
      url "https://github.com/relay-sh/homebrew-tap/releases/download/v#{version}/relay_#{version}_linux_amd64.tar.gz"
    end
  end

  name "relay"
  desc "Relay CLI — connect to databases through Relay agents with data masking"
  homepage "https://userelay.sh"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "relay"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/relay"]
    end
  end

  # No zap stanza required
end
