# This file was generated by GoReleaser. DO NOT EDIT.
cask "relay" do
  version "0.4.0"

  on_macos do
    on_arm do
      sha256 "7a4f1b344eb097f639b7932986ac2903da2e49f0db69c88b03f75acd65334af9"
      url "https://github.com/relay-sh/homebrew-tap/releases/download/v#{version}/relay_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "bba3ef31f613c90fa067ab6e49b9d4b83e9a7a95e50f7ad82cefd17031249fe2"
      url "https://github.com/relay-sh/homebrew-tap/releases/download/v#{version}/relay_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "8ff12c364ad7f99b3efc75838d79eb391cc39af795337336d4f618a7c09ee4db"
      url "https://github.com/relay-sh/homebrew-tap/releases/download/v#{version}/relay_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "085b033e07794385817aa924eebbc3efb892843d81a706358a7f923f60327dd4"
      url "https://github.com/relay-sh/homebrew-tap/releases/download/v#{version}/relay_#{version}_linux_amd64.tar.gz"
    end
  end

  name "relay"
  desc "Relay CLI — connect to databases through Relay agents with data masking"
  homepage "https://userelay.sh"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "relay"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/relay"]
    end
  end

  # No zap stanza required
end
