# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Relay < Formula
  desc "Relay CLI — connect to databases through Relay agents with data masking"
  homepage "https://userelay.sh"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/relay-sh/homebrew-tap/releases/download/v0.1.0/relay_0.1.0_darwin_amd64.tar.gz"
      sha256 "4ca9fc5a575f0a08601d5f1ce6cc7691d4cdd000d3c7ed22cab6b5042d566e5a"

      define_method(:install) do
        bin.install "relay"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/relay-sh/homebrew-tap/releases/download/v0.1.0/relay_0.1.0_darwin_arm64.tar.gz"
      sha256 "db7ad6fa6e6e8dfee6803b4935ecdd28d9167cfd288e6d8be9d78f39cb9148ee"

      define_method(:install) do
        bin.install "relay"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/relay-sh/homebrew-tap/releases/download/v0.1.0/relay_0.1.0_linux_amd64.tar.gz"
      sha256 "d59afc884147ae9ccd829e331222afa3b03339805d0dce09fcec87834ff1324b"
      define_method(:install) do
        bin.install "relay"
      end
    end
  end

  test do
    system "#{bin}/relay", "version"
  end
end
